# Generated by Django 5.2.9 on 2025-12-06 13:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sum', models.DecimalField(decimal_places=2, help_text='Сумма выплаты (должна быть положительной)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма выплаты')),
                ('currency', models.CharField(help_text='Код валюты в формате ISO 4217 (например: USD, EUR, RUB)', max_length=3, verbose_name='Валюта')),
                ('recipients_details', models.TextField(help_text='Банковские реквизиты или платежная информация получателя', verbose_name='Реквизиты получателя')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('closed', 'Закрыта'), ('canselled', 'Отклонена')], db_index=True, default='open', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Опциональное описание или комментарий к заявке', null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payouts_pay_status_e8ed6b_idx'), models.Index(fields=['currency'], name='payouts_pay_currenc_ae64e9_idx'), models.Index(fields=['created_at'], name='payouts_pay_created_69b629_idx')],
            },
        ),
    ]
